// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: business/hello_http.proto

package business

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	HelloHTTP_SayHello_FullMethodName = "/hello_http.HelloHTTP/SayHello"
)

// HelloHTTPClient is the client API for HelloHTTP service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HelloHTTPClient interface {
	// 定义SayHello方法
	SayHello(ctx context.Context, in *HelloHTTPRequest, opts ...grpc.CallOption) (*HelloHTTPResponse, error)
}

type helloHTTPClient struct {
	cc grpc.ClientConnInterface
}

func NewHelloHTTPClient(cc grpc.ClientConnInterface) HelloHTTPClient {
	return &helloHTTPClient{cc}
}

func (c *helloHTTPClient) SayHello(ctx context.Context, in *HelloHTTPRequest, opts ...grpc.CallOption) (*HelloHTTPResponse, error) {
	out := new(HelloHTTPResponse)
	err := c.cc.Invoke(ctx, HelloHTTP_SayHello_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HelloHTTPServer is the server API for HelloHTTP service.
// All implementations must embed UnimplementedHelloHTTPServer
// for forward compatibility
type HelloHTTPServer interface {
	// 定义SayHello方法
	SayHello(context.Context, *HelloHTTPRequest) (*HelloHTTPResponse, error)
	mustEmbedUnimplementedHelloHTTPServer()
}

// UnimplementedHelloHTTPServer must be embedded to have forward compatible implementations.
type UnimplementedHelloHTTPServer struct {
}

func (UnimplementedHelloHTTPServer) SayHello(context.Context, *HelloHTTPRequest) (*HelloHTTPResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedHelloHTTPServer) mustEmbedUnimplementedHelloHTTPServer() {}

// UnsafeHelloHTTPServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HelloHTTPServer will
// result in compilation errors.
type UnsafeHelloHTTPServer interface {
	mustEmbedUnimplementedHelloHTTPServer()
}

func RegisterHelloHTTPServer(s grpc.ServiceRegistrar, srv *interface{}) {
	s.RegisterService(&HelloHTTP_ServiceDesc, srv)
}

func _HelloHTTP_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloHTTPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloHTTPServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HelloHTTP_SayHello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloHTTPServer).SayHello(ctx, req.(*HelloHTTPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HelloHTTP_ServiceDesc is the grpc.ServiceDesc for HelloHTTP service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HelloHTTP_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hello_http.HelloHTTP",
	HandlerType: (*HelloHTTPServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _HelloHTTP_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "business/hello_http.proto",
}
